"""
    Name: Recurrence Model
    Description: Recurrence model class to represent records in Recurrence table of the database
    Author: Magaly Camacho [3072618]

    Date Created: 10/26/2024
    Revisions:
        - 11/01/2024 Magaly Camacho
            Added __repr__() method

    Preconditions: 
        - SQLAlchemy must be installed and configured in the environment
    Postconditions: 
        - None
    Errors/Exceptions: 
        - Validation errors if the attribute constraints (e.g. type, string length, etc.) are not met 
    Side Effects: 
        - Base class will have Recurrence as a part of its metadata
    Invariants: 
        - The class will always be a sub class of the declarative_base from SQLAlchemy
        - The id attribute will always be unique and automatically generated
        - ItemType Enum, Frequency Enum, and Event model are implemented
        - One-to-Many Relationship With Event_
    Known Faults: 
        - None
"""


# Imports
import datetime
from .base import Base # base model
from .event import Event_ # Event model
from .databaseEnums import Frequency # Enum for frequency attribute
from typing import List, Optional
from sqlalchemy.orm import Mapped, mapped_column, relationship


class Recurrence(Base):
    """
    Recurrence Model for records in the Recurrence Table

    Attributes:
        __tablename__ (str): the name of the table
        id (int): recurrence id (primary key, automatically generated by database)
        end_date (datetime): last date of recurrence
        frequency (Models.databaseEnums.Frequency): how often to repeat (daily, weekly, monthly, yearly)
        r_created (datetime): date and time recurrence was created
        r_last_updated (datetime): date and time recurrence was last updated
        events (list[Event_]): events associated with this recurrence
    """
    __tablename__ = "Recurrence"


    # Attributes, all are NOT NULL (required)
    id: Mapped[int] = mapped_column(
        primary_key=True # primary key, automatically generated by database
    ) 

    end_date: Mapped[datetime.datetime]

    frequency: Mapped[Frequency] # daily, weekly, monthly, yearly

    r_created: Mapped[datetime.datetime] = mapped_column(
        default=datetime.datetime.now # defaults to inserted date and time
    )

    r_last_updated: Mapped[datetime.datetime] = mapped_column(
        default=datetime.datetime.now, # defaults to inserted date and time
        onupdate=datetime.datetime.now # auto update this attribute, when record is updated
    )

    # One-to-Many Relationship With Event_
    events: Mapped[Optional[List[Event_]]] = relationship(
        back_populates="reccurence", # attribute
        cascade="all, delete-orphan" # delete recurrence if all of it's events are deleted
    )


    def __repr__(self):
        """String representation of recurrence instance"""
        string = "\nRecurrence("
        string += f"\n\tid={self.id}"
        string += f"\n\tend_date={self.end_date}"
        string += f"\n\tfrequency={self.frequency}"
        string += "\n)\n"

        return string